export  const SEASON ={
    0 : 'Clear sky',
    1 : 'Mainly clear',
    2 : 'Partly cloudy',
    3 : 'Overcast',
    45 : 'Fog',
    48 : 'Depositing rime fog',
    51 : 'Drizzle-light',
    53 : 'Drizzle-moderate',
    55 :'Drizzle-dense intensity',
    56 :'Freezing drizzle-light',
    57 :'Freezing drizzle-dense',
    61 :'Rain-slight',
    63 :'Rain-moderate',
    65 :'Rain-Heavy',
    66 :'Freezing Rain-light',
    67 :'Freezing Rain-heavy',
    71 :'Snow fall-slight',
    73 :'Snow fall-moderate',
    75 :'Snow fall-heavy',
    77 :'Snow grains',
    80 :'Rain shower-slight',
    81 :'Rain shower-moderate',
    82 :'Rain shower-violent',
    85 :'Snow shower slight',
    86 :'Snow shower heavy',
    95 :'Thunderstorm slight or moderate',
    96 : 'Thunderstorm with slight hail',
    99 : 'Thunderstorm with heavy hail',

  }